
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>SIMHOR Automotores</title>
    
</head>

<div class="encabezado">
    <div><h1>SIMHOR Automotores</h1></div>
    <nav>
        <ul>
            <li><a href="<?= BASE_URL ?>home">Todos los Vehículos</a></li>
            <li><a href="<?= BASE_URL ?>items">Ver Categorias</a></li>
            <li><a href="<?= BASE_URL ?>concesionarias">Concesionarias</a></li>
            <li><a href="<?= BASE_URL ?>showLogin">Log in</a></li>
            <li><a href="<?= BASE_URL ?>logout">Log out</a></li>
        </ul>
    </nav>
</div>
<body>
