<?php include 'templates/layout/header.phtml';?>
<h3>Vehiculos por Tipo</h3>
<ul>
    <li><a href="router.php?action=tipo&tipo=Camioneta">Camionetas</a></li>
    <li><a href="router.php?action=tipo&tipo=Auto">Autos</a></li>
    <li><a href="router.php?action=tipo&tipo=Suv">Suvs</a></li>
</ul>

<h3>Vehiculos por Marca</h3>
<ul>
    <li><a href="router.php?action=marca&marca=Toyota">Toyota</a></li>
    <li><a href="router.php?action=marca&marca=Ford">Ford</a></li>
    <li><a href="router.php?action=marca&marca=Volkswagen">Volkswagen</a></li>
    <li><a href="router.php?action=marca&marca=Audi">Audi</a></li>
    <li><a href="router.php?action=marca&marca=Mercedes Benz">Mercedes Benz</a></li>
    <li><a href="router.php?action=marca&marca=Chevrolet">Chevrolet</a></li>
</ul>
<?php include 'templates/layout/footer.phtml';?>
