<form action="add" method="POST" class="my-4">
    <div>
        <div>
            <div>
                <label>Marca</label>
                <input required name="marca" type="text">
            </div>
        </div>

        <div>
            <div>
                <label>Modelo</label>
                <input required name="modelo" type="text">
            </div>
        </div>
        <div>
            <div>
                <label>Año</label>
                <input required name="año" type="number">
            </div>
        </div>
        <div>
            <div>
                <label>Tipo</label>
                <input required name="tipo" type="text">
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>


