<?php require 'templates/layout/header.phtml' ?>


<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>


<h1>Presa Automotores</h1>
    <h3>Inicio de Sesión</h3>
        <form method='post' action='login'>
            <label for='username'>Usuario:</label>
            <input type='text' id='username' name='username' required>
            
            <label for='password'>Contraseña:</label>
            <input type='password' id='password' name='password' required>
            
            <button type='submit'>Iniciar Sesión</button>
        </form>



<?php require 'templates/layout/footer.phtml' ?>
